services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    hostname: zookeeper
    ports:
      - '2181:2181'
    restart: always
    environment:
      - ZOO_TICK_TIME=2000
      - ALLOW_ANONYMOUS_LOGIN=yes

  snapcache:
    image: apache/kvrocks:2.7.0
    restart: always
    ports:
      - '6666:6666'
    entrypoint: "kvrocks"
    command: ["--dir", "/kvrocks_data", "-c", "/var/lib/kvrocks/kvrocks.conf", "--pidfile", "/var/run/kvrocks/kvrocks.pid", "--bind", "0.0.0.0", "--rocksdb.write_options.sync", "yes"]
