services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    hostname: zookeeper
    ports:
      - '2181:2181'
    restart: always
    environment:
      - ZOO_TICK_TIME=2000
      - ALLOW_ANONYMOUS_LOGIN=yes

  redis:
    hostname: redis
    image: redis:7.2
    restart: always
    ports:
      - '6379:6379'
